waveform_params:
  channels: "AE"
  modes:  [[2,2], [2,1], [3,3], [3,2], [4,4], [4,3]]
  noise: "sangria"
  duration: 1 # weeks
  dt: 100 # seconds

prior:
  "logMchirp": [5.2, 5.3] # log10(Mchirp/Msun)
  "q":    [1,5]
  "chi1": [0,0]
  "chi2": [0,0]
  "dist": [10,10]  # dist in Gpc (note that we shall sample uniformly dist^3)
  "phi": [0.0, 0.0]
  "inc": [0.5 ,0.5] # cos inclination
  "lambda": [3.14,3.14] # ecliptic longitude
  "beta": [0.0,0.0] # sin ecliptic latitude
  "psi": [1.0, 1.0]
  "Deltat": [ -1, -0.9] # t_merger from end of observation in days
